func throwingFunc() throws {
    return
}
func foo() {
    do {
try throwingFunc()
} catch {
<#code#>
}
}
